### ISSUE TITLE
No support for multi_search endpoint

### ISSUE THREAD

**Issue by briep-bixly** [swiftype/swiftype-py#21]
Swiftype offers an endpoint to perform multiple queries in the same request, but that endpoint isn't included in this package.
https://swiftype.com/documentation/app-search/api/search

**Comment by JasonStoltz** [comment]
Hey @briep-bixly. That endpoint is for our App Search product. This issue is you've created is for our Site Search client. Our App Search client does cover that endpoint: https://github.com/swiftype/swiftype-app-search-python#multi-search
